#!/bin/bash
mongoexport -db stuszynski -c ufo -o export.json -jsonArray

#Proba naprawy bazy
node JSONfixer.js

#Czyszczenie bazy
curl -X DELETE http://127.0.0.1:5984/stuszynski

#Wkladanie danych
curl -X PUT http://127.0.0.1:5984/stuszynski
curl -X POST -H "Content-Type: application/json" --data @export.json http://127.0.0.1:5984/stuszynski/_bulk_docs
